CREATE TABLE T_ACTIVITI_ROLE 
(
	ID VARCHAR(40) NOT NULL, 
    CODE VARCHAR(40), 
    NAME VARCHAR(40), 
	TYPE VARCHAR(10), 
	constraint PK_T_ACTIVITI_ROLE primary key (ID)
);

comment on table T_ACTIVITI_ROLE is
'业务角色';
comment on column T_ACTIVITI_ROLE.ID is
'UUID';
comment on column T_ACTIVITI_ROLE.CODE is
'角色编码';
comment on column T_ACTIVITI_ROLE.NAME is
'角色名称';
comment on column T_ACTIVITI_ROLE.TYPE is
'类型';

CREATE TABLE T_ACTIVITI_USER 
(
	ID VARCHAR(40) NOT NULL, 
	EMAIL VARCHAR(255), 
    CODE VARCHAR(40), 
    NAME VARCHAR(40), 
	PASSWORD VARCHAR(40), 
	constraint PK_T_ACTIVITI_USER primary key (ID)
);

comment on table T_ACTIVITI_USER is
'业务用户';
comment on column T_ACTIVITI_USER.EMAIL is
'邮箱';
comment on column T_ACTIVITI_USER.CODE is
'用户编码';
comment on column T_ACTIVITI_USER.NAME is
'用户名称';
comment on column T_ACTIVITI_USER.PASSWORD is
'用户密码';

CREATE TABLE T_ACTIVITI_USER_ROLE 
(
	USER_ID VARCHAR(40) NOT NULL, 
	ROLE_ID VARCHAR(40) NOT NULL
);
comment on table T_ACTIVITI_USER_ROLE is
'用户角色关系表';
alter table T_ACTIVITI_USER_ROLE add constraint FK_T_ACTIVITI_USER_ROLE_USER_ID foreign key (ROLE_ID) references T_ACTIVITI_ROLE (ID);
alter table T_ACTIVITI_USER_ROLE add constraint FK_T_ACTIVITI_USER_ROLE_ROLE_ID foreign key (USER_ID) references T_ACTIVITI_USER (ID);

CREATE TABLE T_ACTIVITI_DEPARTMENT 
(
	ID VARCHAR(40) NOT NULL, 
	NAME VARCHAR(128), 
	constraint PK_T_ACTIVITI_DEPARTMENT primary key (ID)
);
comment on table T_ACTIVITI_DEPARTMENT is
'组织表';
comment on column T_ACTIVITI_DEPARTMENT.ID is
'UUID';
comment on column T_ACTIVITI_DEPARTMENT.NAME is
'组织名称';
CREATE TABLE T_ACTIVITI_LEAVE
(
	ID VARCHAR(40) NOT NULL, 
	NAME VARCHAR(128), 
	constraint PK_T_ACTIVITI_LEAVE primary key (ID)
);
comment on table T_ACTIVITI_LEAVE is
'请假表';
comment on column T_ACTIVITI_LEAVE.ID is
'UUID';
comment on column T_ACTIVITI_LEAVE.NAME is
'请假名称';

CREATE TABLE T_SYSTEM_PERMISSION
(
    ID VARCHAR(40) NOT NULL, 
    NAME VARCHAR(128), 
    CODE VARCHAR(128), 
    FOLDER BOOLEAN NOT NULL, 
    PID VARCHAR(40),
    URL VARCHAR(256),
    STATUS integer,
    CONSTRAINT PK_T_SYSTEM_PERMISSION PRIMARY KEY (ID)
);
COMMENT ON TABLE T_SYSTEM_PERMISSION IS
'菜单表';
COMMENT ON COLUMN T_SYSTEM_PERMISSION.ID IS
'UUID';
COMMENT ON COLUMN T_SYSTEM_PERMISSION.NAME IS
'菜单名称';
COMMENT ON COLUMN T_SYSTEM_PERMISSION.CODE IS
'菜单编码';
COMMENT ON COLUMN T_SYSTEM_PERMISSION.FOLDER IS
'是否父级';
COMMENT ON COLUMN T_SYSTEM_PERMISSION.PID IS
'父菜单ID';
COMMENT ON COLUMN T_SYSTEM_PERMISSION.URL IS
'功能链接';
COMMENT ON COLUMN T_SYSTEM_PERMISSION.STATUS IS
'菜单状态';
ALTER TABLE T_SYSTEM_PERMISSION ADD CONSTRAINT FK_T_SYSTEM_PERMISSION FOREIGN KEY (PID) REFERENCES T_SYSTEM_PERMISSION;